name: EGYM to Strava Sync

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:      # Manueller Start m√∂glich

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install requests python-dotenv PyGithub

      - name: Run Sync
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          EGYM_TENANT: ${{ secrets.EGYM_TENANT }}
          EGYM_EMAIL: ${{ secrets.EGYM_EMAIL }}
          EGYM_PASSWORD: ${{ secrets.EGYM_PASSWORD }}
          STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
          STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
          STRAVA_REFRESH_TOKEN: ${{ secrets.STRAVA_REFRESH_TOKEN }}
        run: python main.py
